move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-10_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-10_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-10_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-10_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-11_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-11_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-11_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-11_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-12_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-12_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-12_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2009-12_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-10_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-10_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-10_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-10_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-11_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-11_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-11_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-11_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-12_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-12_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-12_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-12_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-1_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-1_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-2_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-2_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-2_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-2_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-3_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-3_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-3_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-3_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-4_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-4_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-4_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-4_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-5_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-5_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-5_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-5_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-6_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-6_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-6_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-6_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-7_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-7_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-7_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-7_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-8_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-8_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-9_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-unidades-2010-9_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-10_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-10_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-10_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-10_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-10_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-10_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-11_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-11_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-11_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-11_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-11_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-11_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-12_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-12_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-12_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-12_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-12_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2009-12_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-10_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-10_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-10_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-10_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-10_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-10_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-10_4.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-10_4.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-11_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-11_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-11_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-11_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-11_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-11_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-11_4.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-11_4.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_4.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_4.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_5.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-12_5.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-1_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-1_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-1_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-1_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-2_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-2_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-2_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-2_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-2_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-2_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-3_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-3_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-3_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-3_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-4_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-4_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-4_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-4_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-4_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-4_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-5_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-5_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-5_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-5_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-5_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-5_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-6_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-6_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-6_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-6_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-6_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-6_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-7_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-7_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-7_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-7_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-7_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-7_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-8_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-8_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-8_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-8_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-8_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-8_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-9_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-9_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-9_2.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-9_2.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-9_3.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-varios-2010-9_3.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2009-10_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2009-10_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2009-11_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2009-11_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2009-12_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2009-12_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-10_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-10_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-11_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-11_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-12_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-12_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-1_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-1_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-2_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-2_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-3_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-3_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-4_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-4_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-5_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-5_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-6_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-6_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-7_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-7_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-8_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-8_1.xml
move z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-9_1.xml.txt z:\impexp\falabella_co\data\forecast\import\pwm_frc-vtas-pesos-2010-9_1.xml
